// <auto-generated />
using System;
using Garage_2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20220203105046_ChangeVehicleType")]
    partial class ChangeVehicleType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NoOfWheels")
                        .HasColumnType("int");

                    b.Property<bool>("Parked")
                        .HasColumnType("bit");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2022, 2, 3, 11, 50, 46, 405, DateTimeKind.Local).AddTicks(644),
                            Brand = "Volvo",
                            Color = "Svart",
                            Model = "V60",
                            NoOfWheels = 4,
                            Parked = true,
                            RegNo = "FHX010",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2022, 2, 3, 11, 50, 46, 405, DateTimeKind.Local).AddTicks(697),
                            Brand = "Toyota",
                            Color = "Blå",
                            Model = "Celica Supra",
                            NoOfWheels = 4,
                            Parked = true,
                            RegNo = "HHS407",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2022, 2, 3, 11, 50, 46, 405, DateTimeKind.Local).AddTicks(701),
                            Brand = "Mercedes-Benz",
                            Color = "Vit",
                            Model = "Arocs",
                            NoOfWheels = 6,
                            Parked = true,
                            RegNo = "XRE565",
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2022, 2, 3, 11, 50, 46, 405, DateTimeKind.Local).AddTicks(704),
                            Brand = "Scania",
                            Color = "Svart",
                            Model = "",
                            NoOfWheels = 8,
                            Parked = true,
                            RegNo = "MLB803",
                            VehicleType = 3
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2022, 2, 3, 11, 50, 46, 405, DateTimeKind.Local).AddTicks(707),
                            Brand = "BMV",
                            Color = "Svart",
                            Model = "",
                            NoOfWheels = 6,
                            Parked = true,
                            RegNo = "MXW413",
                            VehicleType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
