// <auto-generated />
using System;
using Garage_2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20220202102723_c2")]
    partial class c2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NoOfWheels")
                        .HasColumnType("int");

                    b.Property<bool>("Parked")
                        .HasColumnType("bit");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("vehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3614),
                            Brand = "Volvo",
                            Color = "Black",
                            Model = "V60",
                            NoOfWheels = 4,
                            Parked = false,
                            RegNo = "FHX010",
                            vehicleType = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3666),
                            Brand = "Toyota",
                            Color = "Blue",
                            Model = "Celica Supra",
                            NoOfWheels = 4,
                            Parked = false,
                            RegNo = "HHS407",
                            vehicleType = 1
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3671),
                            Brand = "Mercedes-Benz",
                            Color = "White",
                            Model = "Arocs",
                            NoOfWheels = 6,
                            Parked = false,
                            RegNo = "XRE565",
                            vehicleType = 3
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3675),
                            Brand = "Scania",
                            Color = "Black",
                            Model = "",
                            NoOfWheels = 8,
                            Parked = false,
                            RegNo = "MLB803",
                            vehicleType = 4
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3679),
                            Brand = "BMV",
                            Color = "Black",
                            Model = "",
                            NoOfWheels = 6,
                            Parked = false,
                            RegNo = "MXW413",
                            vehicleType = 2
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3683),
                            Brand = "Mercedes-Benz",
                            Color = "Black",
                            Model = "CX30",
                            NoOfWheels = 4,
                            Parked = false,
                            RegNo = "DRE065",
                            vehicleType = 4
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3686),
                            Brand = "Scania",
                            Color = "Black",
                            Model = "Venus",
                            NoOfWheels = 6,
                            Parked = false,
                            RegNo = "DLB103",
                            vehicleType = 4
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new DateTime(2022, 2, 2, 11, 27, 22, 768, DateTimeKind.Local).AddTicks(3690),
                            Brand = "Tesla",
                            Color = "White",
                            Model = "Zeta",
                            NoOfWheels = 4,
                            Parked = false,
                            RegNo = "FX0413",
                            vehicleType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
